sudo: required
dist: trusty
cache: apt
os: linux

language:
  - cpp

env:
  global:
    - GH_REPO_NAME: Wagner
    - GH_REPO_REF: github.com/PhDP/Wagner.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

matrix:
  include:
    - env: BUILD=DEBUG
      compiler: gcc

    - env: BUILD=RELEASE
      compiler: gcc

    - env: BUILD=DEBUG
      compiler: clang

    - env: BUILD=RELEASE
      compiler: clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang-5.0 gcc-7 g++-7 libarmadillo-dev libgmp-dev libgmp10

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-5.0"; fi
  - wget https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz
  - tar xf cmake-3.8.2.tar.gz
  - cd cmake-3.8.2
  - ./configure
  - make
  - sudo make install
  - cd ..
  - PROJECT_DIR=`pwd`
  - BOOST=$HOME/boost
  - git clone --depth 1 -b boost-1.63.0 https://github.com/boostorg/boost.git $BOOST
  - cd $BOOST
  - git submodule update --init --merge
  - ./bootstrap.sh
  - ./b2 headers
  - cd $PROJECT_DIR

script:
  - export BOOST_ROOT=$BOOST
  - $CXX --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake .. -DBuildTests=On -DCMAKE_BUILD_TYPE=${BUILD} -DBOOST_ROOT="$BOOST_ROOT"
  - make
  - ./test/wagner_tests
